# Generated by Django 5.2.4 on 2025-08-08 21:58

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='نام کامل')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='آدرس ایمیل')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True, unique=True, verbose_name='شماره تلفن')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='تاریخ تولد')),
                ('gender', models.CharField(blank=True, choices=[('M', 'مرد'), ('F', 'زن'), ('O', 'سایر')], max_length=1, null=True, verbose_name='جنسیت')),
                ('skin_type', models.IntegerField(blank=True, choices=[(1, 'خشک'), (2, 'چرب'), (3, 'مختلط'), (4, 'حساس'), (5, 'نرمال')], null=True, verbose_name='نوع پوست')),
                ('skin_concerns', models.JSONField(blank=True, default=list, verbose_name='نگرانی\u200cهای پوستی')),
                ('preferences', models.JSONField(blank=True, default=list, verbose_name='ترجیحات محصولات')),
                ('wishlist', models.JSONField(blank=True, default=list, verbose_name='لیست علاقه\u200cمندی\u200cها')),
                ('address', models.TextField(blank=True, null=True, verbose_name='آدرس کامل')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='شهر')),
                ('postal_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='کد پستی')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='حساب کاربری')),
            ],
            options={
                'verbose_name': 'پروفایل کاربر',
                'verbose_name_plural': 'پروفایل\u200cهای کاربران',
                'indexes': [models.Index(fields=['email'], name='Users_profi_email_db8eab_idx'), models.Index(fields=['phone_number'], name='Users_profi_phone_n_4b2ece_idx')],
            },
        ),
    ]
