# Generated by Django 5.2.4 on 2025-08-05 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_Id', models.UUIDField(verbose_name='User-Id')),
                ('name', models.CharField(max_length=300, verbose_name='user-name')),
                ('email', models.EmailField(max_length=254, verbose_name='user-email')),
                ('device_type', models.TextField(max_length=300, verbose_name='mobile/desktop')),
                ('concerns', models.JSONField(default=list)),
                ('preferences', models.JSONField(default=list)),
            ],
        ),
    ]
