# Generated by Django 5.2.4 on 2025-09-11 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='skin_concerns',
            field=models.TextField(blank=True, verbose_name='مشکلات پوستی'),
        ),
    ]
