# Generated by Django 5.2.4 on 2025-08-10 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'User profile', 'verbose_name_plural': 'User profiles'},
        ),
        migrations.AddField(
            model_name='profile',
            name='pocket',
            field=models.IntegerField(default=1000, verbose_name='موجودی'),
        ),
        migrations.AddField(
            model_name='profile',
            name='views_product',
            field=models.JSONField(blank=True, default=list, verbose_name='مشاهده شده ها'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='preferences',
            field=models.JSONField(blank=True, default=list, verbose_name='مورد پسندها'),
        ),
    ]
