# Generated by Django 5.2.4 on 2025-08-11 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_alter_profile_options_profile_pocket_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='skin_concerns',
            field=models.TextField(blank=True, verbose_name='نگرانی\u200cهای پوستی'),
        ),
    ]
