# Generated by Django 5.2.4 on 2025-08-05 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_alter_users_info_options_users_info_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='users_info',
            name='skin_type',
            field=models.IntegerField(choices=[(1, 'Dry'), (2, 'Oily'), (3, 'Combination'), (4, 'Sensitive')], null=True, verbose_name='Skin Type'),
        ),
        migrations.AlterField(
            model_name='users_info',
            name='device_type',
            field=models.CharField(max_length=300, verbose_name='mobile/desktop'),
        ),
    ]
