# Generated by Django 5.2.4 on 2025-08-06 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_users_info_skin_type_alter_users_info_device_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='users_info',
            name='likes_products',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='users_info',
            name='wishlist',
            field=models.JSONField(default=list),
        ),
    ]
