# Generated by Django 5.2.4 on 2025-08-08 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_users_info_likes_products_users_info_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='users_info',
            name='inventory',
            field=models.IntegerField(default=0, verbose_name='inventory'),
        ),
        migrations.AlterField(
            model_name='users_info',
            name='User_Id',
            field=models.UUIDField(unique=True, verbose_name='User-Id'),
        ),
    ]
