# Generated by Django 5.2.4 on 2025-08-15 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0002_ingredients_tags_remove_product_integrations_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='views_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
