# Generated by Django 5.2.4 on 2025-08-08 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuizResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default='', max_length=300)),
                ('age', models.PositiveSmallIntegerField()),
                ('sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=6)),
                ('weather', models.CharField(choices=[('Dry and warm', 'Dry and warm'), ('Humid and warm', 'Humid and warm'), ('Dry and cold', 'Dry and cold'), ('Humid and cold', 'Humid and cold')], default='Dry and warm', max_length=14)),
                ('skin_type', models.CharField(choices=[('Dry', 'Dry'), ('Oily', 'Oily'), ('Combination', 'Combination'), ('Sensitive', 'Sensitive')], default='Dry', max_length=11)),
                ('skin_moisture', models.CharField(choices=[('Dehydrated', 'Dehydrated'), ('Balanced', 'Balanced'), ('Excessively oily', 'Excessively oily')], default='Dehydrated', max_length=16)),
                ('skin_texture', models.CharField(choices=[('Smooth', 'Smooth'), ('Rough', 'Rough')], default='Smooth', max_length=6)),
                ('skin_sensitivity', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3)),
                ('sun_exposure', models.CharField(choices=[('Low', 'Low'), ('Moderate', 'Moderate'), ('High', 'High')], default='Moderate', max_length=8)),
                ('favorite_product_type', models.CharField(choices=[('Cream', 'Cream'), ('Oil', 'Oil'), ('Gel', 'Gel'), ('Serum', 'Serum')], default='Cream', max_length=5)),
                ('if_allergic', models.CharField(default='', max_length=300)),
            ],
        ),
    ]
