# Generated by Django 5.2.4 on 2025-08-13 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizresults',
            name='username_user',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
    ]
