# Generated by Django 5.2.4 on 2025-09-11 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageAnalysisResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username_user', models.CharField(default='unknown', max_length=300)),
                ('skin_concerns', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.AddField(
            model_name='quizresults',
            name='api_response',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quizresults',
            name='image_analysis_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
