# Generated by Django 5.2.4 on 2025-09-12 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0002_alter_imageanalysisresults_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='imageanalysisresults',
            table=None,
        ),
    ]
