# Generated by Django 5.2.4 on 2025-08-15 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0002_quizresults_username_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizresults',
            name='sex',
            field=models.CharField(choices=[('مرد', 'Male'), ('Female', 'Female')], default='مرد', max_length=6),
        ),
    ]
