# Generated by Django 5.2.4 on 2025-08-07 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0003_quizresults_delete_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizresults',
            name='full_name',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='quizresults',
            name='if_allergic',
            field=models.CharField(default='', max_length=300),
        ),
    ]
