# Generated by Django 5.2.4 on 2025-09-12 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0003_alter_imageanalysisresults_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skincareroutine',
            old_name='username',
            new_name='username_user',
        ),
    ]
