# Generated by Django 5.2.4 on 2025-08-15 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0004_alter_quizresults_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizresults',
            name='sex',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=6),
        ),
    ]
