# Generated by Django 5.2.4 on 2025-08-15 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0005_alter_quizresults_sex'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizresults',
            name='skin_concerns',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='quizresults',
            name='if_allergic',
            field=models.TextField(blank=True),
        ),
    ]
