# Generated by Django 5.2.4 on 2025-08-15 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0006_quizresults_skin_concerns_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizresults',
            name='skin_concerns',
            field=models.TextField(blank=True, default=''),
        ),
    ]
