# Generated by Django 5.2.4 on 2025-08-15 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0007_alter_quizresults_skin_concerns'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkinCareRoutine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('routine', models.TextField()),
            ],
        ),
    ]
