# Generated by Django 5.2.4 on 2025-08-16 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0008_skincareroutine'),
    ]

    operations = [
        migrations.AddField(
            model_name='skincareroutine',
            name='username',
            field=models.CharField(default='unknown', max_length=300),
        ),
    ]
